spring.application.name=perfulandia-pruebasunitarias
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3307/perfulandia?serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=

# configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# configuración de logs (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html
